version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lab11_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: lab11_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure

volumes:
  pgdata: